[theme]
primaryColor = "#e62429"
backgroundColor = "#07060a"
secondaryBackgroundColor = "#100c14"
textColor = "#f0f2f8"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
